In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.io import loadmat

%matplotlib inline

In [3]:
# 加载matlab文件用 scipy.loadmat
data = loadmat('ex3data1.mat')
data

{'X': array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        ..., 
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.]]),
 '__globals__': [],
 '__header__': b'MATLAB 5.0 MAT-file, Platform: GLNXA64, Created on: Sun Oct 16 13:09:09 2011',
 '__version__': '1.0',
 'y': array([[10],
        [10],
        [10],
        ..., 
        [ 9],
        [ 9],
        [ 9]], dtype=uint8)}

In [4]:
sigmoid = lambda z: (1 / (1 + np.exp(-z)))

In [50]:
# Cost Function
def cost(theta, X, y, learningRate):
    X = np.matrix(X)
    y = np.matrix(y)
    theta = np.matrix(theta.T)   
    [m, n] = X.shape

    h = sigmoid(X * theta.T) # (m x n) * (n x 1) = (m x 1)
    
    first = -y.T * np.log(h)
    second = (1 - y).T * np.log(1 - h)
    reg = (learningRate / (2 * m)) * np.sum(np.power(theta[:,1:theta.shape[1]], 2))

    J_theta = np.sum(first - second) / m
    
    return J_theta

In [9]:
def gradientWithReg(theta, X, y, learningRate):
    X = np.matrix(X)
    y = np.matrix(y)
    theta = np.matrix(theta.T)
    [m, n] = X.shape
    grad = np.zeros(n)

    error = sigmoid(X * theta.T) - y   # (m x 1)
    
    for j in range(n):
        theta_j = np.multiply(error, X[:, j])
        reg = (learningRate / m) * theta[:, j]
        if (j == 0) :
            grad[j] = np.sum(theta_j) / m
        else:
            grad[j] = np.sum(theta_j) / m + reg
        
    return grad

In [34]:
# Gradient Function
def gradient(theta, X, y, learningRate):
    X = np.matrix(X)  # (m x n)
    y = np.matrix(y)
    theta = np.matrix(theta.T)
    error = sigmoid(X * theta.T) - y   # (m x 1)
    [m, n] = X.shape
#     grad = np.zeros(n)  
#     for j in range(n):
#         theta_j = np.multiply(error, X[:, j])
#         grad[j] = np.sum(theta_j) / m
    reg = (learningRate / m) * theta
    grad = ((X.T * error) / m).T + reg
#                         m x 1   m x 1  
    grad[0, 0] = np.sum((error.T * X[:, 0]) / m)
    return np.array(grad).ravel()

In [7]:
import scipy.optimize as opt

In [30]:
def oneVsAll(X, y, num_labels, learningRate):
    [m, n] = X.shape
    all_theta = np.zeros((num_labels, n + 1))
#     all_theta = np.zeros((10, n + 1))
    
    
    # Add 'One' to X data matrix
    X = np.insert(X, 0, values=np.ones(m), axis=1)
    
    for i in range(1, num_labels + 1):
        theta = np.zeros(n + 1)
#       label = 1 2 3 4 5 ... ...
        y_i = np.array([1 if label == i else 0 for label in y])
        y_i = np.reshape(y_i, (m, 1))
        
        # minimize the objective function
#         fmin = opt.minimize(fun=cost, x0=theta, args=(X, y_i, learningRate), method='tnc', jac=gradient)
        fmin = opt.minimize(fun=cost, x0=theta, args=(X, y_i, learningRate), jac=gradient)
        all_theta[i - 1, :] = fmin.x
    return all_theta

In [14]:
[m, n] = data['X'].shape
m, n

(5000, 400)

In [15]:
all_theta = np.zeros((10, n + 1))
all_theta

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [17]:
X = np.insert(data['X'], 0, values=np.ones(m), axis=1)
X

array([[ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 1.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 1.,  0.,  0., ...,  0.,  0.,  0.]])

In [18]:
theta = np.zeros(n+1)
theta

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0

In [20]:
y_0 = np.array([1 if label == 0 else 0 for label in data['y']])
y_0 = np.reshape(y_0, (m, 1))
y_0

array([[0],
       [0],
       [0],
       ..., 
       [0],
       [0],
       [0]])

In [21]:
X.shape, y_0.shape, theta.shape, all_theta.shape

((5000, 401), (5000, 1), (401,), (10, 401))

In [22]:
np.unique(data['y'])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=uint8)

In [51]:
all_theta = oneVsAll(data['X'], data['y'], 10, 1)

In [52]:
all_theta.shape, X.shape, theta.shape

((10, 401), (5000, 401), (401,))

In [53]:
def predict_all(X, all_theta):
    [m, n] = X.shape
    num_labels = all_theta.shape[0]
    
    X = np.insert(X, 0, values=np.ones(m), axis=1)
    X = np.matrix(X)
    
    h = sigmoid(X * all_theta.T)
    
    return np.argmax(h, axis=1) + 1
    

In [54]:
y_predict = predict_all(data['X'], all_theta)

In [55]:
correct = [1 if a == b else 0 for (a, b) in zip(y_predict, data['y'])]
accuracy = (sum(map(int, correct)) / float(len(correct)))
print('Accuracy = {}'.format(accuracy * 100))

Accuracy = 93.4
